### PR TITLE
Support for Qt5 and KF5 updates

### LINKED ISSUE #13: Semi-automatic Qt and KF updates
With the large set of Qt and KF5 packages, we need to figure out how to ensure that they all are up to date. For that, I suggest to write scripts that would allow us:

1. checkout all Qt / KF5 repos in sailfishos-chum, update them to new version (upstream and rpm spec), tag accordingly, and upload back to Github
2. update all _service files at OBS (chum:testing or chum, possible to select)

To tackle SFOS updates:

3. we would need a script that would allow us to enable or disable SFOS versions in _service as a build target for all Qt / KF packages 

While it is possible for most of the packages, some have exceptions:
- Qt WebEngine has its own release schedule and its own versions
- Some KF5 packages (qqc2-breeze-style) have their own versions

Those exceptional packages will have to be excluded from `1` and `2`, but still get `3`.

I think to make it happen, we need:

- repo designated for development of such scripts. I suggest to use this repo (qt5). Its just we cannot rebuild it "for fun" at OBS as it triggers whole Qt/KF rebuild. But scripts used outside of regular Qt install should be OK
- config file that would list all Qt and KF5 packages (separate configs?) and whether they are skipped for auto-increment of the version. this file should map github repo and OBS package names
- decide what to use for scripting: shell? probably shell is sufficient, but then will have to be clever with config file format - ideally to simply exclude by some keyword lines with non-automatic packages

### PR DESCRIPTION
**Pull request by rinigus**
This PR adds scripts and documentation for updates of Qt and KF5 packages. Added scripts follow the approach proposed in #13 allowing us:

1. checkout all Qt / KF5 repos in sailfishos-chum, update them to new version (upstream and rpm spec), tag accordingly, and upload back to Github
2. update all _service files at OBS (chum:testing or chum, possible to select)
3. enable or disable SFOS versions in OBS meta as a build target for all Qt / KF packages 

So far, scripts were tested against few packages in https://build.sailfishos.org/project/show/home:rinigus:qt515:packaging and checked out in my GitHub https://github.com/rinigus/ . All worked as expected.

When PR is merged, I suggest that I would perform update of KF5 to 5.105.0. That way we can test it in production as well.

Fixes #13

### CODE REVIEW

**Comment by piggz** [comment]
Does this handle multiple packaging versions for a particular qt/kf5 version, eg, by using +gitN notation for tags in the packaging repo?

**Comment by rinigus** [comment]
Yes, it does. Example test at 

- GitHub repo: https://github.com/rinigus/qtsvg/tags
- OBS https://build.sailfishos.org/package/show/home:rinigus:qt515:packaging/qtsvg

Now, more specifically how it works:

Source update script:

- When you update sources, KF5 would be tagged with just the version you wanted (5.105.0). 

- Qt5 would try to checkout kde/5.15 branch, find your Qt version (5.15.9) tag and offset against it (number of commits applied after the release tag). That way, we get 5.15.9+kde3 (here 3 commits were added to fix latest release). In case of KDE branch, they actually rebase whole thing and after 5.15.10 will come out, patches will be applied to that. So, we couldn't get 5.15.9 anymore. If it is the case, then just Qt version is checked out (5.15.9) and tagged accordingly.

- If we had our earlier version 5.15.8+git1, that would stay and new tag will be just 5.15.9+kde3. Manually, we can add +git1 on top of it.

Update OBS package script:

- This should get just the tag with the largest version number. This should take into account +git1

Example package case:
- real version was [5.15.9+kde7](https://github.com/rinigus/qtsvg/releases/tag/5.15.9%2Bkde7)
- I have added tag to the same commit 5.15.9+kde12

At OBS, you can see that _service points to 5.15.9+kde12. Sources are detected as +kde7, as OBS sees the same commit tagged twice.

I haven't tested +kde12+git1 yet - that should work I think

**Comment by rinigus** [comment]
Tested locally by adding tag 5.15.9+kde7+git1:

```
➜  qtsvg git:(main) git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags . '*.*.*'
30590c41b31b4abaa64ce94364a4571b25b27980        refs/tags/5.15.7
906aac5181aefbde96f74e3bddfb9370eb16026c        refs/tags/5.15.9
906aac5181aefbde96f74e3bddfb9370eb16026c        refs/tags/5.15.9+kde7
906aac5181aefbde96f74e3bddfb9370eb16026c        refs/tags/5.15.9+kde7+git1
906aac5181aefbde96f74e3bddfb9370eb16026c        refs/tags/5.15.9+kde12
```

That shows tags sorting - observe that `5.15.9+kde7+git1` is after `5.15.9+kde7` but before `5.15.9+kde12`. As it should. So, here the last "winning" one would be `5.15.9+kde12`

**Comment by piggz** [comment]
OK, lgtm

**Comment by rinigus** [comment]
Thank you very much!

**Pull request merged**
